language: python
python:
  - "3.5"
  - "3.6"
  #- "3.7-dev"
  - "pypy-5.3.1"


allow_failures:
  #- python: "3.7-dev"
  - python: "pypy-5.3.1"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest
script:
  - py.test
