language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade -r requirements-dev.txt
script:
  - py.test test --cov=sindy --flake8
# We can remove the --token option once we move to a public repo 
after_success:
  - codecov --token=9d40a0bb-0bfb-44d5-a01b-9f32fff65e56