language: python
python:
  - "3.6"
  - "3.7-dev"
  #- "pypy-5.3.1"
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade -r requirements-dev.txt
script:
  - flake8 sparsereg
  - py.test test --cov=sparsereg
after_success:
  - codecov
deploy:
  provider: pypi
  user: ohjeah
  password: $PYPI_PW
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
    all_branches: true
