language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade -r requirements-dev.txt
script:
  - pytest test --flake8
  # - pytest test --cov=sindy --flake8
# env should be removed once we set up a *public* repo
# env:
#   - CODECOV_TOKEN=9d40a0bb-0bfb-44d5-a01b-9f32fff65e56
# after_success:
#   - codecov