language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install --upgrade -r requirements-dev.txt
script:
  - pytest test --flake8
  # - pytest test --cov=sindy
# after_success:
#   - codecov